[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyquipu-engine"
version = "0.1.1"
authors = [{ name="doucx", email="doucxldh@gmail.com" }]
description = "The state and history engine for Quipu, powered by Git plumbing."
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Version Control",
    "Typing :: Typed",
]
keywords = ["quipu", "devops", "engine", "state", "git"]

[project.urls]
Homepage = "https://github.com/quipu-dev/Quipu"
Repository = "https://github.com/quipu-dev/Quipu"
"Bug Tracker" = "https://github.com/quipu-dev/Quipu/issues"
dependencies = [
    "pyquipu-interfaces ~= 0.1.0",
    "pyquipu-common ~= 0.1.0",
    "pyquipu-bus ~= 0.1.0",
    "pyyaml >= 6.0",
]

[tool.uv.sources]
pyquipu-interfaces = { workspace = true }
pyquipu-common = { workspace = true }
pyquipu-bus = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/quipu"]