[project]
name = "pyquipu"
version = "0.1.2"
description = "Quipu: Process Archaeology for the AI Era (Meta-package)"
authors = [{ name="doucx", email="doucxldh@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Environment :: Console",
    "Topic :: Software Development :: Version Control",
    "Topic :: Software Development :: Build Tools",
]
keywords = ["quipu", "devops", "cli", "tui", "git", "history", "automation", "ai"]

dependencies = [
    "pyquipu-application ~= 0.1.1",
    "pyquipu-bus ~= 0.1.1",
    "pyquipu-cli ~= 0.1.1",
    "pyquipu-common ~= 0.1.1",
    "pyquipu-engine ~= 0.1.1",
    "pyquipu-interfaces ~= 0.1.1",
    "pyquipu-runtime ~= 0.1.1",
]

[project.urls]
Homepage = "https://github.com/quipu-dev/Quipu"
Repository = "https://github.com/quipu-dev/Quipu"
"Bug Tracker" = "https://github.com/quipu-dev/Quipu/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/quipu"]
