[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyquipu-common"
version = "0.1.0"
authors = [{ name="doucx", email="doucxldh@gmail.com" }]
description = "Common utilities and helpers for the Quipu ecosystem."
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/quipu"]