[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyquipu-application"
version = "0.1.0"
authors = [{ name="doucx", email="doucxldh@gmail.com" }]
description = "Core application logic for Quipu, orchestrating engine and runtime."
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyquipu-interfaces ~= 0.1.0",
    "pyquipu-engine ~= 0.1.0",
    "pyquipu-runtime ~= 0.1.0",
    "pyquipu-common ~= 0.1.0",
    "pyquipu-bus ~= 0.1.0",
]

[tool.uv.sources]
pyquipu-interfaces = { workspace = true }
pyquipu-engine = { workspace = true }
pyquipu-runtime = { workspace = true }
pyquipu-common = { workspace = true }
pyquipu-bus = { workspace = true }

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true