[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyquipu-application"
version = "0.3.0"
authors = [{ name="doucx", email="doucxldh@gmail.com" }]
description = "Core application logic for Quipu, orchestrating engine and runtime."
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Build Tools",
    "Typing :: Typed",
]
keywords = ["quipu", "devops", "history", "git", "engine"]

dependencies = [
    "pyquipu-spec ~= 0.1.1",
    "pyquipu-engine ~= 0.3.0",
    "pyquipu-runtime ~= 0.3.0",
    "pyquipu-common ~= 0.2.0",
]

[project.urls]
Homepage = "https://github.com/quipu-dev/Quipu"
Repository = "https://github.com/quipu-dev/Quipu"
"Bug Tracker" = "https://github.com/quipu-dev/Quipu/issues"

[tool.uv.sources]
pyquipu-spec = { workspace = true }
pyquipu-engine = { workspace = true }
pyquipu-runtime = { workspace = true }
pyquipu-common = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/quipu"]