[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyquipu-bus"
version = "0.1.0"
authors = [{ name="doucx", email="doucxldh@gmail.com" }]
description = "Message bus and event orchestration for the Quipu ecosystem."
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyquipu-common ~= 0.1.0",
]

[tool.uv.sources]
pyquipu-common = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/quipu"]